/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.ImageIcon;

/**
 *
 * @author Abner
 */
public class Menu_principal extends javax.swing.JFrame {

    C_resistencias cr = new C_resistencias();
    C_capacitores cc = new C_capacitores();
    C_RLC RLC = new C_RLC();
    Integrantes intg = new Integrantes();
    
    public Menu_principal() {
        initComponents();
        
        //edicion de ventana principal
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono_principal.png")).getImage());
        this.setLocationRelativeTo(this);
        rsutilities.RSUtilities.setCentrarVentana(this);
        rsutilities.RSUtilities.setMoverVentana(this);
        rsutilities.RSUtilities.setOpaqueVentana(this, false);
        //fin de la edicion de ventana principal
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_fondoPrincipal = new javax.swing.JPanel();
        bt_salir = new javax.swing.JButton();
        pn_menu = new javax.swing.JPanel();
        bt_cResistencias = new rojerusan.RSButtonIconI();
        bt_cCapacitores = new rojerusan.RSButtonIconI();
        bt_cRLC = new rojerusan.RSButtonIconI();
        lb_encabezado = new javax.swing.JLabel();
        lb_titulo = new javax.swing.JLabel();
        Aiuda = new javax.swing.JButton();
        lb_titulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fisix | Menu principal");
        setUndecorated(true);
        setResizable(false);

        pn_fondoPrincipal.setBackground(new java.awt.Color(102, 102, 102));

        bt_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bt_salir.setToolTipText("Bye, bye...");
        bt_salir.setBorderPainted(false);
        bt_salir.setContentAreaFilled(false);
        bt_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lloraras.png"))); // NOI18N
        bt_salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tristin.png"))); // NOI18N
        bt_salir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lloraras.png"))); // NOI18N
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });

        pn_menu.setBackground(new java.awt.Color(51, 51, 51));

        bt_cResistencias.setBackground(new java.awt.Color(51, 51, 51));
        bt_cResistencias.setBorder(null);
        bt_cResistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/resistencia.png"))); // NOI18N
        bt_cResistencias.setText("Resistencias");
        bt_cResistencias.setToolTipText("Calcula los elementos de un circuito de resistencias (Voltaje, Intensidad y Resistencia)");
        bt_cResistencias.setActionCommand("Circuito Resistencias");
        bt_cResistencias.setBorderPainted(false);
        bt_cResistencias.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_cResistencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cResistencias.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bt_cResistencias.setInheritsPopupMenu(true);
        bt_cResistencias.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamos.png"))); // NOI18N
        bt_cResistencias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamos.png"))); // NOI18N
        bt_cResistencias.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamos.png"))); // NOI18N
        bt_cResistencias.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamos.png"))); // NOI18N
        bt_cResistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cResistenciasActionPerformed(evt);
            }
        });

        bt_cCapacitores.setBackground(new java.awt.Color(51, 51, 51));
        bt_cCapacitores.setBorder(null);
        bt_cCapacitores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/capacitor.png"))); // NOI18N
        bt_cCapacitores.setText("Capacitores");
        bt_cCapacitores.setToolTipText("Calcula los elementos de un circuito de capacitores (Carga, Capacitancia y Voltaje)");
        bt_cCapacitores.setActionCommand("Circuito Capacitores");
        bt_cCapacitores.setBorderPainted(false);
        bt_cCapacitores.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_cCapacitores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cCapacitores.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bt_cCapacitores.setInheritsPopupMenu(true);
        bt_cCapacitores.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamos.png"))); // NOI18N
        bt_cCapacitores.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamos.png"))); // NOI18N
        bt_cCapacitores.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamos.png"))); // NOI18N
        bt_cCapacitores.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamos.png"))); // NOI18N
        bt_cCapacitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cCapacitoresActionPerformed(evt);
            }
        });

        bt_cRLC.setBackground(new java.awt.Color(51, 51, 51));
        bt_cRLC.setBorder(null);
        bt_cRLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circuito.png"))); // NOI18N
        bt_cRLC.setText("Circuito RLC");
        bt_cRLC.setToolTipText("Calcula los elementos de un circuito RLC");
        bt_cRLC.setBorderPainted(false);
        bt_cRLC.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_cRLC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cRLC.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bt_cRLC.setInheritsPopupMenu(true);
        bt_cRLC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamos.png"))); // NOI18N
        bt_cRLC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamos.png"))); // NOI18N
        bt_cRLC.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamos.png"))); // NOI18N
        bt_cRLC.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamos.png"))); // NOI18N
        bt_cRLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cRLCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_menuLayout = new javax.swing.GroupLayout(pn_menu);
        pn_menu.setLayout(pn_menuLayout);
        pn_menuLayout.setHorizontalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_cResistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_cCapacitores, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
            .addComponent(bt_cRLC, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        );
        pn_menuLayout.setVerticalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(bt_cResistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cCapacitores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cRLC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        lb_encabezado.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lb_encabezado.setForeground(new java.awt.Color(255, 255, 255));
        lb_encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_principal.png"))); // NOI18N
        lb_encabezado.setText("Menu Principal | Fisix 0.1");
        lb_encabezado.setToolTipText("Este es un titulo, y no hace mas que ser un titulo");
        lb_encabezado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lb_titulo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(204, 204, 204));
        lb_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trueno.png"))); // NOI18N
        lb_titulo.setText("INICIO | FISIX");
        lb_titulo.setToolTipText("Titulo");

        Aiuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aiuda.png"))); // NOI18N
        Aiuda.setToolTipText("Da click para ver a estos cracks ");
        Aiuda.setBorderPainted(false);
        Aiuda.setContentAreaFilled(false);
        Aiuda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loco.png"))); // NOI18N
        Aiuda.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loco.png"))); // NOI18N
        Aiuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AiudaActionPerformed(evt);
            }
        });

        lb_titulo1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lb_titulo1.setForeground(new java.awt.Color(204, 204, 204));
        lb_titulo1.setText("<html> Como parte del proyecto final para la clase de <b>FISICA II</b>,  \n<br>se ha desarrollado este programa capaz de calcular los valores de los circuitos de:<br/><br/>   \n\n1.<i> Resistencias</i><br/>  \n2.<i> Capacitores</i><br/>   \n3. <i>RLC (Resistencia, Inductor y Capacitor)</i><br/><br/>       \n\n Para cada uno es posible resolver circuitos con conexiones <u>paralelas</u> y en  <u>serie</u>.<br/><br/>      \n Selecciona la operacion que deseas realizar e ingresa los valores solicitados  y define la variable a calcular.");
        lb_titulo1.setToolTipText("Un breve resumen, no espere mucho de esto. lo programe a las 2:00am");

        javax.swing.GroupLayout pn_fondoPrincipalLayout = new javax.swing.GroupLayout(pn_fondoPrincipal);
        pn_fondoPrincipal.setLayout(pn_fondoPrincipalLayout);
        pn_fondoPrincipalLayout.setHorizontalGroup(
            pn_fondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_fondoPrincipalLayout.createSequentialGroup()
                .addComponent(pn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pn_fondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_fondoPrincipalLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pn_fondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_fondoPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_fondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_fondoPrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Aiuda, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_fondoPrincipalLayout.createSequentialGroup()
                                .addComponent(lb_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                                .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        pn_fondoPrincipalLayout.setVerticalGroup(
            pn_fondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_fondoPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_fondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Aiuda, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_fondoPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_fondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_salirActionPerformed

    private void bt_cResistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cResistenciasActionPerformed
        cr = new C_resistencias(); 
        cr.setVisible(true);
    }//GEN-LAST:event_bt_cResistenciasActionPerformed

    private void bt_cCapacitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cCapacitoresActionPerformed
        cc = new C_capacitores();
        cc.setVisible(true);
    }//GEN-LAST:event_bt_cCapacitoresActionPerformed

    private void bt_cRLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cRLCActionPerformed
        RLC = new C_RLC();
        RLC.setVisible(true);
    }//GEN-LAST:event_bt_cRLCActionPerformed

    private void AiudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AiudaActionPerformed
        intg = new Integrantes();
        intg.setVisible(true);
    }//GEN-LAST:event_AiudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aiuda;
    private rojerusan.RSButtonIconI bt_cCapacitores;
    private rojerusan.RSButtonIconI bt_cRLC;
    private rojerusan.RSButtonIconI bt_cResistencias;
    private javax.swing.JButton bt_salir;
    private javax.swing.JLabel lb_encabezado;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JLabel lb_titulo1;
    private javax.swing.JPanel pn_fondoPrincipal;
    private javax.swing.JPanel pn_menu;
    // End of variables declaration//GEN-END:variables
}
